### ISSUE TITLE
super resolution question

### ISSUE THREAD

**Issue by xiaosean** [pfnet-research/sngan_projection#17]
Hi,
I have some questions about the super resolution.

Q1.I don't see super resolution part code. Is this part actually made in this version?
Q2. In paper : CGANS WITH PROJECTION DISCRIMINATOR
equation (10
![image](https://user-images.githubusercontent.com/11615161/40548441-4f9bda42-6067-11e8-87c0-a4312ba503a0.png)
![image](https://user-images.githubusercontent.com/11615161/40548487-78fa473e-6067-11e8-8f9c-034ae4faed92.png)
Q2-1:what is the the y's k parameter(yij**k**) 
Q2-2:Can I imagine it is a 128 downsample picture with y inner product then sum?
Q2-3:if so how to use 2d inner product, and what's that means?

thanks in advanced!

**Comment by takerum** [comment]
Sorry for the late reply.
Q1: the basic architecture is the same as the one used the conditional image generation model. I can open-source after I clean-up the experimental code. 
Q2-1: k is the channel index and k={1, 2, 3} because `y` is a RGB down-sampled image. 
Q2-2: y is a 32 downsample picture.
Q2-3: We reshape y and F \in R^{32x32x3} into the vector of shape R^{32\*32\*3} and then calculate inner product between them.

**Comment by xiaosean** [comment]
thank you for your reply!

**Comment by NeuralBricolage** [comment]
Hi, 
do you still plan to open source the super resolution code? I have nice images generated with SNGAN_projection (256X256), thank you, and i would like to upscale them to something like at least 512X512 - do you think it's even possible esp provided i have a single GTX 1080 TI?
Appreciate any suggestions!

**Comment by takerum** [comment]
Hi, 

These are the commits for the super resolution: https://github.com/pfnet-research/sngan_projection/pull/32. (I have not fully checked yet that it reproduces the paper's results)

We used 4gpus when running the super resolution experiments from 32x32 to 128x128.
I have not tried with 512x512, but you can still run the code if you reduce the channel size of the models.

**Comment by NeuralBricolage** [comment]
thank you! i will try it asap
