### ISSUE TITLE
Wrong evaluation of Lipschitz norm of a convolutional layer?

### ISSUE THREAD

**Issue by aiueogawa** [pfnet-research/sngan_projection#37]
Hi, I have a question about your implementation to evaluate Lipschitz norm of a convolutional layer.

You follow the following instruction described in [Spectral Norm Regularization for Improving the Generalizability of Deep Learning](https://arxiv.org/abs/1705.10941).

> Convolutions. We describe how to handle convolutions because they are used widely in recent applications of deep neural networks. Consider a convolutional layer with a input channels, b output channels, and a w × h-sized kernel. This implies that the convolution has abwh parameters. Note that a value in an output channel is determined using awh values in the input channels. Hence, we align the parameters as a matrix of size b × awh and apply the abovementioned power iteration method to the matrix to calculate its spectral norm and gradient.

I wonder how this evaluation method is justified.

Actually, the operation in a convolution layer can be rewritten as matrix-vector product (weight-input product) by unrolling the kernel (abwh parameters) into the corresponding sparse Toeplitz matrix and unrolling the input vector along the spacial dimension, as described in https://stackoverflow.com/questions/16798888/2-d-convolution-as-a-matrix-matrix-multiplication.
Hence I think this unrolled kernel should be used as the matrix to calculate its spectral norm.

In your implementation, the kernel (matrix) to calculate its spectral norm should be [k1 k2 k3 k4] if I use the notation in the above link.

Is it OK?

**Comment by takerum** [comment]
Hi,

Yes, you should use the unrolled matrix if you want to estimate the exact spectral norm of the convolution operator.
The reasons why we use the reshaped matrix in our paper are because
1: we tried spectral normalization(SN) with the unrolled matrix, but it did not make any significant improvement over SN with the reshaped matrix, in terms of the inception score. 
2: the computational time of SN with the reshaped matrix is a bit faster than SN with the unrolled matrix.

Also, there is relationship between the spectral norm of the reshape matrix and unrolled matrix; please see Corollary 1 in (Tsuzuku et al., 2018, https://arxiv.org/abs/1802.04034).
k * (spectral norm of the reshape matrix) is an upper bound on (spectral norm of the unrolled matrix) where k is a constant.

**Comment by aiueogawa** [comment]
@takerum 
Thank you for your answer!

I have another question.
You evaluate a Lipschitz (spectral) norm of a weight matrix in terms of a L2 norm, resulting in evaluation of a maximum singular value of its matrix, which involves some approximation (power iteration, reshape vs unroll).
Why do you use L2 norm to evaluate a Lipschitz (spectral) norm?

**Comment by takerum** [comment]
Your qustions is why we choose "L2" norm?
It's because we tried normalizing by L1 and L_infinity matrix norm but both were inferior to the L2 normalization in terms of the score.

**Comment by aiueogawa** [comment]
@takerum
Thanks for all!
